# Generated by Django 3.0.8 on 2020-09-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crmaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('token', models.CharField(max_length=200, verbose_name='token')),
            ],
        ),
    ]
