# Generated by Django 3.0.8 on 2020-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id_megaplan', models.CharField(max_length=10, verbose_name='Сделка')),
                ('tipe_of_deal', models.CharField(max_length=10, verbose_name='Сделка')),
                ('employee', models.CharField(max_length=25, verbose_name='Сотрудник')),
                ('call_len', models.CharField(default='пока нет данных атс', max_length=25, verbose_name='Длительность разговора')),
                ('result', models.CharField(default='пока нет данных атс', max_length=25, verbose_name='Результат звонка')),
                ('in_crm', models.CharField(default='пока нет данных атс', max_length=5, verbose_name=' Добавлено в CRM')),
            ],
        ),
    ]
