# Generated by Django 3.0.8 on 2020-09-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0002_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='customer_number',
            field=models.CharField(default='', max_length=25, verbose_name='Номер клиента'),
        ),
        migrations.AddField(
            model_name='call',
            name='emploee_number',
            field=models.CharField(default='Номер скрыт', max_length=25, verbose_name='Номер сотрудника'),
        ),
        migrations.AlterField(
            model_name='call',
            name='tipe_of_deal',
            field=models.CharField(max_length=10, verbose_name='Тип сделки'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Клиент')),
                ('call', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='call_app.Call')),
            ],
        ),
    ]
