# Generated by Django 3.0.8 on 2020-09-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0003_auto_20200920_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='emploee_number',
            new_name='employee_number',
        ),
    ]
