# Generated by Django 3.0.8 on 2020-09-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0004_auto_20200921_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='customer_number',
            field=models.CharField(default='Номер скрыт', max_length=50, verbose_name='Номер клиента'),
        ),
        migrations.AlterField(
            model_name='call',
            name='deal_id_megaplan',
            field=models.CharField(max_length=50, verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='call',
            name='employee',
            field=models.CharField(max_length=50, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='call',
            name='employee_number',
            field=models.CharField(default='Номер скрыт', max_length=50, verbose_name='Номер сотрудника'),
        ),
        migrations.AlterField(
            model_name='call',
            name='tipe_of_deal',
            field=models.CharField(max_length=50, verbose_name='Тип сделки'),
        ),
    ]
