# Generated by Django 3.0.8 on 2020-09-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0005_auto_20200921_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_len',
            field=models.CharField(default='пока нет данных атс', max_length=50, verbose_name='Длительность разговора'),
        ),
        migrations.AlterField(
            model_name='call',
            name='in_crm',
            field=models.CharField(default='пока нет данных атс', max_length=10, verbose_name=' Добавлено в CRM'),
        ),
        migrations.AlterField(
            model_name='call',
            name='result',
            field=models.CharField(default='пока нет данных атс', max_length=50, verbose_name='Результат звонка'),
        ),
    ]
