# Generated by Django 3.0.8 on 2020-09-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0007_auto_20200921_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.Call'),
        ),
    ]
