# Generated by Django 3.0.8 on 2020-09-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0008_auto_20200921_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='call',
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(default='Junior', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Друг', max_length=50, verbose_name='Имя'),
        ),
    ]
