# Generated by Django 3.0.8 on 2020-09-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0009_auto_20200921_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='call_app.Customer'),
        ),
    ]
