# Generated by Django 3.0.8 on 2020-09-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0010_call_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='call_app.Customer'),
        ),
    ]
